# Site settings
title: Spritey Blog
description: >
  Spritey is an open source sprite sheet creator. It is implemented
  in Java with SWT and JFace front end. This tool is one of the most
  efficient sprite sheet packers which can pack a large amount of sprites
  in less than a second. You can find out about its progress, functionality
  and implementation in the project blog, pivotal tracker or github. Links
  can be found in a side bar..
baseurl: "/spritey"
url: "http://bykovskyy.com"

# Build settings
markdown: kramdown
